export { AboutSection } from "./about-section";
export { ContentSection } from "./content-section";
export { EducationSection } from "./education-section";
export { ExtracurricularsSection } from "./extracurriculars-section";
export { HeroSection } from "./hero-section";
export { OpeningScreen } from "./opening-screen";
export { ProjectsSection } from "./projects-section";
export { SectionShell } from "./section-shell";
export { SkillsSection } from "./skills-section";
